name: EKS Helm Client Github Action
on:
  push:
    branches:
      - master
jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Install & upgrade Helm chart on EKS
        uses: open-source-srilanka/eks-helm-client-github-action@v1.0.0
        env:
          REGION_CODE: ap-southeast-1
          CLUSTER_NAME: eks-client-cluster
        with:
          args: >
            bash -c "
              helm repo add bitnami https://charts.bitnami.com/bitnami;
              helm repo update;
              helm install bitnami/mysql --generate-name
            "
           
